export const staticResourcePaths = {
  s3_bucket_cdn: 'https://d1izo6k8ekr0p2.cloudfront.net/',
  s3_asset_bucket: 'https://everlite-video-assets.s3.ap-south-1.amazonaws.com/',
  horizontalScreening: [
    './assets/horizontalScreeningImages/LotusL.jpg',
    './assets/horizontalScreeningImages/LoveL.jpg',
    './assets/horizontalScreeningImages/MariposaL.jpg',
    './assets/horizontalScreeningImages/RajwadaL.jpg',
    './assets/horizontalScreeningImages/SpectraL.jpg',
    './assets/horizontalScreeningImages/SrutiL.jpg',
  ],
  videoBranding: [
    './assets/videoBranding/mariposa.webm',
    './assets/videoBranding/love.webm',
    './assets/videoBranding/sutra.webm',
    './assets/videoBranding/lotus.webm',
    './assets/videoBranding/rajwada.webm',
    './assets/videoBranding/spectra.webm',
  ],
  //this from left to right
  mainStageSidePanelVideos: {
    // older 
    // portrait1: `https://d1izo6k8ekr0p2.cloudfront.net/Aham_vertical.webm`,
    // portrait2: `https://d1izo6k8ekr0p2.cloudfront.net/everlite_vertical.webm`,
    // landscape1: `https://d1izo6k8ekr0p2.cloudfront.net/CRAFTSMANSHIP_DIAMOND_horizontal.webm`,
    // landscape2: `https://d1izo6k8ekr0p2.cloudfront.net/CRAFTSMANSHIP_FOR_GOLD_horizontal.webm`,

    // new compressed and without audio
    portrait1: `https://d1izo6k8ekr0p2.cloudfront.net/Aham_vertical_480_without_audio.mp4`,
    portrait2: `https://d1izo6k8ekr0p2.cloudfront.net/everlite_vertical_480_WithoutAudio.mp4`,
    landscape1: `https://d1izo6k8ekr0p2.cloudfront.net/CRAFTSMANSHIP_DIAMOND_horizontal_360_without_audio.mp4`,
    landscape2: `https://d1izo6k8ekr0p2.cloudfront.net/CRAFTSMANSHIP_FOR_GOLD_horizontal_360_without_audio.mp4`,
  },
  jewelleryEnvMapTexture: './assets/jewelleryEnvMap.hdr',
  sky: './assets/sky.hdr',
  mainSkyTexture: './assets/skybox/forBackground/',
  tvScreen: './assets/Screens/TV1.glb',
  reusableDiamondMesh: './assets/jewellery/diamondComponent.glb',
  grassLeafBlade: {
    diffuse: './assets/grassTextures/blade_diffuse.jpg',
    alpha: './assets/grassTextures/blade_alpha.jpg',
  },
  gltfFilePaths: {
    feb: './assets/avatars/feb.glb',
    may: './assets/avatars/may.glb',
    yBot: './assets/avatars/yBot.gltf',
    guide: './assets/avatars/guide.gltf',
    sia : './assets/avatars/Female.glb'
  },
  arrow: './assets/avatars/arrow.glb',
  imagePreviewPaths: {
    feb: './assets/images/febAvatarPreview.png',
    may: './assets/images/mayAvatarPreview.png',
  },
  dummyTriGltf: './assets/dummyTri.gltf',
  portalMesh: './assets/portal/portal_circle.glb',
  inventoryConsole: {
    display: './assets/inventoryConsole/displayCentered.glb',
    body: './assets/meteor/leaderboardHighLODWithoutScreen.glb',
    buttonColliders: './assets/inventoryConsole/buttonColliders.glb',
  },
  // newEnvironment: './assets/map_store5_chains_added.glb',  
  newEnvironment: './assets/world.glb',
  waterNormalsTexture: './assets/images/waternormals.jpg',
  groupInfo: './assets/groupReferences/groupInfo.glb',
  groupInfoOGStore: './assets/groupReferences/groupInfoOGStore.glb',
  groupInfoToUpdate: './assets/groupReferences/groupInfoWithUpdates27April.glb',
  rainbowTexture: './assets/images/rainbow.jpg',
  defaultRing: './assets/jewelleryDefaultTemplates/defaultRing.glb',
  defaultEarring: './assets/jewelleryDefaultTemplates/defaultEarring.glb',
  defaultPendant: './assets/jewelleryDefaultTemplates/defaultPendant.glb',
  defaultBracelet: './assets/jewelleryDefaultTemplates/defaultBracelet.glb',
  defaultNecklace: './assets/jewelleryDefaultTemplates/defaultNecklace.glb',

  asteroidBaseColorTexture: './assets/meteor/baseColor.png',
  asteroidMetallicRoughnessTexture: './assets/meteor/metallicRoughness.png',
  asteroidNormalTexture: './assets/meteor/normal.png',
  asteroidDiamondMesh: './assets/meteor/diamondMeteor.glb',
  asteroidMetalMesh: './assets/meteor/metalMeteor.glb',
  asteroidCollideRocks: './assets/meteor/rocks.glb',
  asteroidCollider: './assets/meteor/meteorCollider.glb',
  axe: './assets/meteor/axe.glb',
  metalNugget: './assets/meteor/nugget.glb',
  diamondNugget: './assets/meteor/diamondNugget.glb',
  goldTwoDImage: './assets/meteor/gold.png',
  silverTwoDImage: './assets/meteor/silver.png',
  diamondTwoDImage: './assets/meteor/diamond.png',
  redeemMachineHighLOD: './assets/meteor/redeemMachineHighLODWithoutScreen.glb',
  redeemMachineLowLOD: './assets/meteor/redeemMachineLowLODWithoutScreen.glb',
  redeemMachineAlbedoTransparency:
    './assets/meteor/redeemMachineAlbedoTransparency.png',
  redeemMachineMetallicRoughness:
    './assets/meteor/redeemMachineMetallicRoughness.png',
  redeemMachineScreen: './assets/meteor/redeemMachineScreen.glb',
  leaderboardMachineHighLOD:
    './assets/meteor/leaderboardHighLODWithoutScreen.glb',
  leaderboardMachineLowLOD:
    './assets/meteor/leaderboardLowLODWithoutScreen.glb',

  rajdhaniFont: './assets/fonts/Rajdhani-Bold.ttf',
  stageLightsWithAnim: './assets/lights_with_anim.glb',

  diamondMeteorTrailSprite: './assets/meteorTrailSpriteDIAMOND.png',
  goldMeteorTrailSprite: './assets/meteorTrailSpriteGOLD.png',
  silverMeteorTrailSprite: './assets/meteorTrailSpriteSILVER.png',
  meteorTrailSpriteData: './assets/meteorTrailSprite.json',
  meteorGroundImpactSprite: './assets/meteorGroundImpactSprite.png',
  meteorGroundImpactSpriteData: './assets/meteorGroundImpactSprite.json',
  listOfMaleAvatars: [
    'https://models.readyplayer.me/67165eda1be09e846ccacc27.glb',
    'https://models.readyplayer.me/67165efc1be09e846ccacccc.glb',
    'https://models.readyplayer.me/67165f4d73dbbee1a775c215.glb',
    'https://models.readyplayer.me/67165f6f25a7639d7d732eaf.glb',
    'https://models.readyplayer.me/67165f972c50c0c5ebff91a1.glb',
  ],
  listOfFemaleAvatars: [
    'https://models.readyplayer.me/66fd1456becde09d86683ca3.glb',
    'https://models.readyplayer.me/67165df12c50c0c5ebff8a13.glb',
    'https://models.readyplayer.me/663410190f8b88612aa74a4a.glb',
    'https://models.readyplayer.me/67165fc5ab70b0473564e624.glb',
    'https://models.readyplayer.me/67165fe025a7639d7d73305e.glb',
    'https://models.readyplayer.me/671660051be09e846ccad14e.glb',
  ],
  danceAnims: [
    './assets/Dance1.glb',
    './assets/Dance2.glb',
    './assets/Dance3.glb',
    './assets/Dance4.glb',
    './assets/Dance5.glb',
    './assets/Dance6.glb',
    './assets/Dance7.glb',
    './assets/Dance8.glb',
  ],

  axeSound: './assets/sounds/axeSound.mp3',
  chaChingSound: './assets/sounds/chaChing.mp3',
  meteorFallingSound: './assets/sounds/meteorFalling.mp3',
  jewelleryItemForVRShwocase: './assets/vr/jewelleryItems/GLR-D000705677_h.glb',
  teleportCollider: './assets/vr/teleport_map_no_mats_joined.glb',
  hybridScreenUIContent:{
    cart: './assets/hybridScreenUI/shopping_cart.png',
    arrow : './assets/hybridScreenUI/next_arrow.png',
    bracelet: './assets/hybridScreenUI/bracelet.webp',
    chain: './assets/hybridScreenUI/chain.webp',
    earrings: './assets/hybridScreenUI/earring.webp',
    necklace: './assets/hybridScreenUI/necklace.webp',
    ring: './assets/hybridScreenUI/ring.webp',
    pendant: './assets/hybridScreenUI/pendant.webp',
    portrait:{
      everlite: './assets/hybridScreenUI/portrait/everlite.png',
      mariposa: './assets/hybridScreenUI/portrait/mariposa.png',
      rajwada: './assets/hybridScreenUI/portrait/rajwada.png',
      // cera: './assets/hybridScreenUI/portrait/cera.png',
      sutra: './assets/hybridScreenUI/portrait/sutra.png',
      sruti: './assets/hybridScreenUI/portrait/sruti.png',
      love: './assets/hybridScreenUI/portrait/love.png',
    },
    landscape:{
      everlite: './assets/hybridScreenUI/landscape/everlite.png',
      mariposa: './assets/hybridScreenUI/landscape/mariposa.jpeg',
      rajwada: './assets/hybridScreenUI/landscape/rajwada.jpg',
      // cera: './assets/hybridScreenUI/landscape/cera.png',
      sutra: './assets/hybridScreenUI/landscape/sutra.jpeg',
      sruti: './assets/hybridScreenUI/landscape/sruti.png',
      love: './assets/hybridScreenUI/landscape/love.jpg',
    }
  },
  bigScreenAudio: 'https://d1izo6k8ekr0p2.cloudfront.net/big_screen_audio.mp3',
  bigScreenVideo: 'https://d1izo6k8ekr0p2.cloudfront.net/big_screen_video.mp4',
  // introVideo: 'https://d1izo6k8ekr0p2.cloudfront.net/jan_2024_intro_video.webm',
  introVideo: 'https://d1izo6k8ekr0p2.cloudfront.net/intro_video_480_compressed.mp4',
}
