/*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  forwardRef,
  ForwardRefRenderFunction,
  useImperativeHandle,
  useMemo,
  useRef,
} from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { useGraph } from '@react-three/fiber'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { SkeletonUtils } from 'three-stdlib'

import { AvatarOptions } from '@client/config/Avatar'

type GLTFResult = GLTF & {
  nodes: {
    Alpha_Surface: THREE.SkinnedMesh
    Alpha_Joints: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Alpha_Body_MAT: THREE.MeshStandardMaterial
    Alpha_Joints_MAT: THREE.MeshStandardMaterial
  }
}

type nodesType = {
  [name: string]: THREE.Object3D<THREE.Event>
} & GLTFResult['nodes']

export interface AvatarModelRef {
  animationActions: Record<string, THREE.AnimationAction | null>
}
type AvatarModelProps = JSX.IntrinsicElements['group']
const AVATAR_CONFIG = AvatarOptions.yBot

const YBot: ForwardRefRenderFunction<AvatarModelRef, AvatarModelProps> = (
  props,
  ref,
) => {
  const group = useRef<THREE.Group | null>(null)
  const {
    scene: sceneBeforeCloning,
    materials: materials,
    animations: animations,
  } = useGLTF(AVATAR_CONFIG.gltfFilePath) as GLTFResult
  // we need to clone the skeleton otherwise only one instance of the avatar can be rendered
  // see this for more context - https://github.com/pmndrs/react-three-fiber/issues/245#issuecomment-1214450109
  const scene = useMemo(
    () => SkeletonUtils.clone(sceneBeforeCloning),
    [sceneBeforeCloning],
  )
  const graphOutput = useGraph(scene)
  const nodes = graphOutput.nodes as nodesType
  const { actions } = useAnimations<THREE.AnimationClip>(animations, group)

  useImperativeHandle(ref, () => ({
    animationActions: actions,
  }))

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group
          name='Armature'
          scale={AVATAR_CONFIG.scale}
          position={AVATAR_CONFIG.position}
          rotation={AVATAR_CONFIG.rotation}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name='Alpha_Joints'
            geometry={nodes.Alpha_Joints.geometry}
            material={materials.Alpha_Joints_MAT}
            skeleton={nodes.Alpha_Joints.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name='Alpha_Surface'
            geometry={nodes.Alpha_Surface.geometry}
            material={materials.Alpha_Body_MAT}
            skeleton={nodes.Alpha_Surface.skeleton}
            frustumCulled={false}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(AVATAR_CONFIG.gltfFilePath)

export default forwardRef(YBot)
